# Site settings
title: El meu blog de basquet
email: Jordibasktbdn9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simplement és el meu blog de basquet els que us agrada el disfrutareu!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site

github_username:  jordii9

# Build settings
markdown: kramdown
